// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoXzIXjNSLOelJhy0v4-Bue0uwXQlgSNQ',
    appId: '1:868126027130:web:ea19e3a426014a7dabfac3',
    messagingSenderId: '868126027130',
    projectId: 'cvision-7f747',
    authDomain: 'cvision-7f747.firebaseapp.com',
    storageBucket: 'cvision-7f747.firebasestorage.app',
    measurementId: 'G-JBWG9FCJWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QAi5Gzvq_UExdxf-Lqrqytjw2378nI0',
    appId: '1:868126027130:android:4c27588c65101ccbabfac3',
    messagingSenderId: '868126027130',
    projectId: 'cvision-7f747',
    storageBucket: 'cvision-7f747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgCesSFHW_KPtnBqFsYAZBFKV6uqIJPMU',
    appId: '1:868126027130:ios:6da4781a53a6e8ddabfac3',
    messagingSenderId: '868126027130',
    projectId: 'cvision-7f747',
    storageBucket: 'cvision-7f747.firebasestorage.app',
    iosClientId: '868126027130-ngkjm8mtnb3rbaoidbgviiaptf2k3d0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgCesSFHW_KPtnBqFsYAZBFKV6uqIJPMU',
    appId: '1:868126027130:ios:6da4781a53a6e8ddabfac3',
    messagingSenderId: '868126027130',
    projectId: 'cvision-7f747',
    storageBucket: 'cvision-7f747.firebasestorage.app',
    iosClientId: '868126027130-ngkjm8mtnb3rbaoidbgviiaptf2k3d0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoXzIXjNSLOelJhy0v4-Bue0uwXQlgSNQ',
    appId: '1:868126027130:web:f2449f87451a6a6eabfac3',
    messagingSenderId: '868126027130',
    projectId: 'cvision-7f747',
    authDomain: 'cvision-7f747.firebaseapp.com',
    storageBucket: 'cvision-7f747.firebasestorage.app',
    measurementId: 'G-HCJQXE0XWB',
  );
}
